### ISSUE TITLE
06. API Serving의 2) Model API on Docker Compose설명대로 실행시 에러가 발생합니다.

### ISSUE THREAD

**Issue by oldiron-ho** [mlops-for-mle/tutorial#87]
## Describe the bug
`06. API Serving`의 `2) Model API on Docker Compose` 설명대로 docker-compose.yaml를 작성하고 `docker compose up -d`를 실행하면 `healthcheck.test must start either by "CMD", "CMD-SHELL" or "NONE"` 에러가 발생합니다.

해당 문서는 다음과 같습니다.

https://github.com/mlops-for-mle/tutorial/blob/a45677e17a4ef7f145e544c3cc470b05ecc37d69/docs/api-serving/model-api-on-docker-compose.mdx?plain=1#L113-L122

## To Reproduce
실행시의 환경은 다음과 같습니다.
- docker engine v23.0.4
- docker compose v2.17.2

## Expected behavior

test 배열 처음에 CMD를 추가하면 에러 없이 컨테이너가 실행됩니다.

```
    healthcheck:
      test:
        - CMD
        - curl -X POST http://localhost:8000/predict
        - -H
        - "Content-Type: application/json"
        - -d
        - '{"sepal_length": 6.7, "sepal_width": 3.3, "petal_length": 5.7, "petal_width": 2.1}'
      interval: 10s
      timeout: 5s
      retries: 5
```

## Additional context

해당 내용을 설명하는 Docker 공식 문서 주소 입니다.
https://docs.docker.com/compose/compose-file/05-services/#healthcheck
